environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: aJwAbajByhTfjiB0a3NzwZwWqp5jOJqFaSGelxe7TqgROz+L/QOtmjZj4FtUd029

  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

os: Visual Studio 2017

platform:
  - x64
  - x86

matrix:
  fast_finish: true

install:
  - cmd: git submodule update --init --recursive
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
  - ps: >-
      npm config set progress false
      npm config set spin false
  - ps: >-
      $env:JOBS = "max";
      $env:PUBLISH = "false";
      $env:GIT_TAG = "$(git describe --tags --always HEAD)";
      $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version;
      if ($env:APPVEYOR_REPO_BRANCH -match $env:GIT_TAG) {
        $env:PUBLISH = "true";
      }
      if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -match "[draft]") {
        $env:PUBLISH = "true";
      }
      if ($env:APPVEYOR_REPO_TAG -match "true") {
        $env:PUBLISH = "true";
      }
      true;
  - ps: >-
      @{
        "APPVEYOR_REPO_BRANCH" = $env:APPVEYOR_REPO_BRANCH
        "APPVEYOR_REPO_TAG" = $env:APPVEYOR_REPO_TAG
        "APPVEYOR_REPO_COMMIT_MESSAGE" = $env:APPVEYOR_REPO_COMMIT_MESSAGE
        "LATEST TAG" = $env:GIT_TAG
        "PUBLISHING" = $env:PUBLISH
        "PACKAGE_VERSION" = $env:package_version
      } | Out-String | Write-Host;
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

build_script:
  - npm install --build-from-source
  - ps: .\node_modules\.bin\browserify -o build/lz4.js -r ./lib/utils-js.js:./utils -r buffer -r ./lib/lz4.js:lz4 lib/lz4.js;
  - ps: .\node_modules\.bin\minify build/lz4.js > build/lz4.min.js;

test_script:
  - npm test

after_build:
  - npm run package
  - ps: Get-ChildItem .\build\stage\*\* | %{ Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  release: ${package_version}
  provider: GitHub
  auth_token:
    secure: aJwAbajByhTfjiB0a3NzwZwWqp5jOJqFaSGelxe7TqgROz+L/QOtmjZj4FtUd029
  artifact: /.*\.tar\.gz/
  force_update: true
  draft: true
  prerelease: true
  repository: zeroshade/node-lz4
  on:
    branch: package

